const enc=new TextEncoder();
const SESSION='__Host-aip_session',CSRF='__Host-aip_csrf';
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const b64u=b=>{let s='';for(const x of new Uint8Array(b))s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const unb64u=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a.buffer};
function cookies(req){const out={};for(const p of (req.headers.get('cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim()}return out}
function sameOrigin(req){const u=new URL(req.url),o=req.headers.get('origin');return !!o&&o===u.origin}
function secureCookie(name,value,maxAge,httpOnly=true){return `${name}=${value}; Path=/; Max-Age=${maxAge}; Secure; SameSite=Lax${httpOnly?'; HttpOnly':''}`}
function csrfOk(req){const c=cookies(req)[CSRF],h=req.headers.get('x-csrf-token');return !!c&&!!h&&c===h&&sameOrigin(req)}
async function googleJwks(){const cache=caches.default,key=new Request('https://auth-cache.invalid/google-jwks');const cached=await cache.match(key);if(cached)return cached.json();const upstream=await fetch('https://www.googleapis.com/oauth2/v3/certs',{headers:{accept:'application/json'}});if(!upstream.ok)throw new Error('jwks');const data=await upstream.json();await cache.put(key,new Response(JSON.stringify(data),{headers:{'content-type':'application/json','cache-control':'public, max-age=1800'}}));return data}
async function verifyGoogle(jwt,clientId){if(typeof jwt!=='string'||jwt.length>6000)throw new Error('credential');const parts=jwt.split('.');if(parts.length!==3)throw new Error('credential');let header,payload;try{header=JSON.parse(new TextDecoder().decode(unb64u(parts[0])));payload=JSON.parse(new TextDecoder().decode(unb64u(parts[1])))}catch{throw new Error('credential')}if(header.alg!=='RS256'||!header.kid)throw new Error('alg');const jwks=await googleJwks(),jwk=jwks.keys?.find(k=>k.kid===header.kid&&k.kty==='RSA');if(!jwk)throw new Error('kid');const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,unb64u(parts[2]),enc.encode(`${parts[0]}.${parts[1]}`));if(!ok)throw new Error('signature');const now=Math.floor(Date.now()/1000);if(!['accounts.google.com','https://accounts.google.com'].includes(payload.iss)||payload.aud!==clientId||typeof payload.sub!=='string'||payload.exp<=now||payload.iat>now+300||payload.email_verified!==true)throw new Error('claims');return payload}
async function readSession(req,env){const token=cookies(req)[SESSION];if(!token||!env.GOOGLE_CLIENT_ID)return null;try{return await verifyGoogle(token,env.GOOGLE_CLIENT_ID)}catch{return null}}
async function handleAuth(req,env){const u=new URL(req.url),ready=!!env.GOOGLE_CLIENT_ID;
 if(u.pathname==='/api/auth/config'&&req.method==='GET'){const value=b64u(crypto.getRandomValues(new Uint8Array(24)));return json({googleEnabled:ready,googleClientId:ready?env.GOOGLE_CLIENT_ID:null,reason:ready?null:'Google OAuth yapılandırması tamamlanmadı.',csrf:value},200,{'set-cookie':secureCookie(CSRF,value,1800,false)})}
 if(u.pathname==='/api/auth/session'&&req.method==='GET'){const s=await readSession(req,env);return s?json({authenticated:true,user:{id:s.sub,name:s.name||'',email:s.email||''}}):json({authenticated:false},401)}
 if(u.pathname==='/api/auth/google'&&req.method==='POST'){if(!ready)return json({error:'Google girişi yapılandırılmadı.'},503);if(!csrfOk(req))return json({error:'Geçersiz istek doğrulaması.'},403);if(!(req.headers.get('content-type')||'').startsWith('application/json'))return json({error:'Geçersiz içerik türü.'},415);let body;try{body=await req.json()}catch{return json({error:'Geçersiz JSON.'},400)}try{const g=await verifyGoogle(body.credential,env.GOOGLE_CLIENT_ID),now=Math.floor(Date.now()/1000),ttl=Math.max(1,Math.min(3600,g.exp-now));return json({authenticated:true,user:{id:g.sub,name:g.name||'',email:g.email||''}},200,{'set-cookie':secureCookie(SESSION,body.credential,ttl,true)})}catch{return json({error:'Google kimliği doğrulanamadı.'},401)}}
 if(u.pathname==='/api/auth/logout'&&req.method==='POST'){if(!csrfOk(req))return json({error:'Geçersiz istek doğrulaması.'},403);return json({ok:true},200,{'set-cookie':secureCookie(SESSION,'',0,true)})}
 return json({error:'Not found'},404)}
const PRODUCTS=[
['phishing-explainer','Phishing e-postası açıklayıcı','Siber güvenlik','E-postadaki kırmızı bayrakları ve güvenli sonraki adımları açıklar.'],['cve-prioritizer','CVE özetleyici ve önceliklendirici','Siber güvenlik','CVE risklerini önceliklendirir.'],['soc-triage','SOC alarm triage yardımcısı','Siber güvenlik','Alarm satırlarını ilk inceleme planına dönüştürür.'],['policy-assistant','Güvenlik politikası asistanı','Siber güvenlik','Politika metninde ilgili maddeleri bulur.'],['pr-test-helper','PR açıklaması ve test önerisi üretici','Yazılım','Git diff üzerinden özet ve test önerileri üretir.'],['dependency-risk','Dependency risk açıklayıcı','Yazılım','Dependency bulgularını düzeltme sırasına koyar.'],['docs-assistant','Kurum içi dokümantasyon asistanı','Yazılım','Dokümanlarda yerel arama yapar.'],['release-notes','Release note oluşturucu','Yazılım','Değişiklikleri müşteri dostu sürüm notuna dönüştürür.'],['pdf-quiz','PDF’den quiz üretici','Eğitim','Ders metninden mini quiz üretir.'],['study-planner','Kişisel çalışma planı yardımcısı','Eğitim','Hedeften çalışma planı çıkarır.'],['child-explainer','Çocuklar için konu anlatıcı','Eğitim','Konuyu yaşa göre sadeleştirir.'],['proposal-helper','Teklif hazırlama yardımcısı','İş','Müşteri ihtiyacından teklif taslağı üretir.'],['support-router','Destek talebi sınıflandırıcı','İş','Destek mesajını doğru kuyruğa ayırır.'],['meeting-decisions','Toplantı karar takipçisi','İş','Karar ve görevleri çıkarır.'],['knowledge-assistant','Kurum içi bilgi asistanı','İş','İzinli kaynaklarda yerel arama yapar.'],['video-brief','Video brief ve senaryo hazırlayıcı','İçerik','Kısa video akışı oluşturur.'],['podcast-notes','Podcast not ve önemli an çıkarıcı','İçerik','Transkriptten önemli anları çıkarır.'],['social-calendar','Sosyal içerik takvimi yardımcısı','İçerik','7 günlük içerik takvimi oluşturur.']];
function priceMap(env){try{const v=JSON.parse(env.STRIPE_PRICE_MAP_JSON||'{}');return v&&typeof v==='object'?v:{}}catch{return {}}}
async function stripe(env,path,init={}){if(!env.STRIPE_SECRET_KEY)throw new Error('stripe_not_configured');const r=await fetch(`https://api.stripe.com/v1${path}`,{...init,headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'content-type':'application/x-www-form-urlencoded',...(init.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||'stripe_error');return data}
async function handleCommerce(req,env){const u=new URL(req.url),prices=priceMap(env);
 if(u.pathname==='/api/commerce/catalog'&&req.method==='GET'){return json(PRODUCTS.map(([id,title,category,summary])=>({id,title,category,summary,purchasable:!!prices[id],amount:Number(prices[id]?.amount)||1900,currency:String(prices[id]?.currency||'EUR').toUpperCase()})))}
 if(u.pathname==='/api/commerce/checkout'&&req.method==='POST'){let body;try{body=await req.json()}catch{return json({error:'Geçersiz istek.'},400)}const product=PRODUCTS.find(p=>p[0]===body.productId),cfg=prices[body.productId];if(!product)return json({error:'Uygulama bulunamadı.'},404);if(!cfg?.priceId||!env.STRIPE_SECRET_KEY)return json({error:'Bu uygulama için ödeme henüz yapılandırılmadı.'},503);const s=await readSession(req,env);const form=new URLSearchParams();form.set('mode','payment');form.set('line_items[0][price]',cfg.priceId);form.set('line_items[0][quantity]','1');form.set('success_url',`${u.origin}/store/?purchased=${encodeURIComponent(body.productId)}`);form.set('cancel_url',`${u.origin}/store/`);form.set('client_reference_id',s?.sub||crypto.randomUUID());form.set('metadata[product_id]',body.productId);form.set('customer_creation','always');if(s?.email)form.set('customer_email',s.email);const session=await stripe(env,'/checkout/sessions',{method:'POST',body:form.toString()});return json({url:session.url})}
 if(u.pathname==='/api/commerce/entitlements'&&req.method==='GET'){const s=await readSession(req,env);if(!s?.email||!env.STRIPE_SECRET_KEY)return json({productIds:[]});try{const customers=await stripe(env,`/customers?email=${encodeURIComponent(s.email)}&limit=10`);const ids=new Set();for(const customer of customers.data||[]){const sessions=await stripe(env,`/checkout/sessions?customer=${encodeURIComponent(customer.id)}&status=complete&limit=100`);for(const x of sessions.data||[]){const id=x.metadata?.product_id;if(id)ids.add(id)}}return json({productIds:[...ids]})}catch{return json({productIds:[]})}}
 return json({error:'Not found'},404)}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname.startsWith('/api/auth/'))return handleAuth(req,env);if(u.pathname.startsWith('/api/commerce/'))return handleCommerce(req,env);return env.ASSETS.fetch(req)}};