const enc=new TextEncoder();
const SESSION='__Host-aip_session',CSRF='__Host-aip_csrf';
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const b64u=b=>{let s='';for(const x of new Uint8Array(b))s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const unb64u=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a.buffer};
function cookies(req){const out={};for(const p of (req.headers.get('cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim()}return out}
function sameOrigin(req){const u=new URL(req.url),o=req.headers.get('origin');return !!o&&o===u.origin}
function secureCookie(name,value,maxAge,httpOnly=true){return `${name}=${value}; Path=/; Max-Age=${maxAge}; Secure; SameSite=Lax${httpOnly?'; HttpOnly':''}`}
function csrfOk(req){const c=cookies(req)[CSRF],h=req.headers.get('x-csrf-token');return !!c&&!!h&&c===h&&sameOrigin(req)}
async function googleJwks(){const cache=caches.default,key=new Request('https://auth-cache.invalid/google-jwks');const cached=await cache.match(key);if(cached)return cached.json();const upstream=await fetch('https://www.googleapis.com/oauth2/v3/certs',{headers:{accept:'application/json'}});if(!upstream.ok)throw new Error('jwks');const data=await upstream.json();await cache.put(key,new Response(JSON.stringify(data),{headers:{'content-type':'application/json','cache-control':'public, max-age=1800'}}));return data}
async function verifyGoogle(jwt,clientId){if(typeof jwt!=='string'||jwt.length>6000)throw new Error('credential');const parts=jwt.split('.');if(parts.length!==3)throw new Error('credential');let header,payload;try{header=JSON.parse(new TextDecoder().decode(unb64u(parts[0])));payload=JSON.parse(new TextDecoder().decode(unb64u(parts[1])))}catch{throw new Error('credential')}if(header.alg!=='RS256'||!header.kid)throw new Error('alg');const jwks=await googleJwks(),jwk=jwks.keys?.find(k=>k.kid===header.kid&&k.kty==='RSA');if(!jwk)throw new Error('kid');const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,unb64u(parts[2]),enc.encode(`${parts[0]}.${parts[1]}`));if(!ok)throw new Error('signature');const now=Math.floor(Date.now()/1000);if(!['accounts.google.com','https://accounts.google.com'].includes(payload.iss)||payload.aud!==clientId||typeof payload.sub!=='string'||payload.exp<=now||payload.iat>now+300||payload.email_verified!==true)throw new Error('claims');return payload}
async function readSession(req,env){const token=cookies(req)[SESSION];if(!token||!env.GOOGLE_CLIENT_ID)return null;try{return await verifyGoogle(token,env.GOOGLE_CLIENT_ID)}catch{return null}}
async function handleAuth(req,env){const u=new URL(req.url),ready=!!env.GOOGLE_CLIENT_ID;
 if(u.pathname==='/api/auth/config'&&req.method==='GET'){const value=b64u(crypto.getRandomValues(new Uint8Array(24)));return json({googleEnabled:ready,googleClientId:ready?env.GOOGLE_CLIENT_ID:null,reason:ready?null:'Google OAuth yapılandırması tamamlanmadı.',csrf:value},200,{'set-cookie':secureCookie(CSRF,value,1800,false)})}
 if(u.pathname==='/api/auth/session'&&req.method==='GET'){const s=await readSession(req,env);return s?json({authenticated:true,user:{id:s.sub,name:s.name||'',email:s.email||''}}):json({authenticated:false},401)}
 if(u.pathname==='/api/auth/google'&&req.method==='POST'){if(!ready)return json({error:'Google girişi yapılandırılmadı.'},503);if(!csrfOk(req))return json({error:'Geçersiz istek doğrulaması.'},403);if(!(req.headers.get('content-type')||'').startsWith('application/json'))return json({error:'Geçersiz içerik türü.'},415);let body;try{body=await req.json()}catch{return json({error:'Geçersiz JSON.'},400)}try{const g=await verifyGoogle(body.credential,env.GOOGLE_CLIENT_ID),now=Math.floor(Date.now()/1000),ttl=Math.max(1,Math.min(3600,g.exp-now));return json({authenticated:true,user:{id:g.sub,name:g.name||'',email:g.email||''}},200,{'set-cookie':secureCookie(SESSION,body.credential,ttl,true)})}catch{return json({error:'Google kimliği doğrulanamadı.'},401)}}
 if(u.pathname==='/api/auth/logout'&&req.method==='POST'){if(!csrfOk(req))return json({error:'Geçersiz istek doğrulaması.'},403);return json({ok:true},200,{'set-cookie':secureCookie(SESSION,'',0,true)})}
 return json({error:'Not found'},404)}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname.startsWith('/api/auth/'))return handleAuth(req,env);return env.ASSETS.fetch(req)}};
